name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Use Node.js version from .nvmrc
        run: |
          expected_version=$(cat .nvmrc)
          if [[ "$expected_version" != "$(node --version)" ]]; then
            echo "Installing Node.js version $expected_version..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install "$expected_version"
            nvm use "$expected_version"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
