import './globals.css';
import { Inter } from 'next/font/google';
import Menu from '../components/UI/Menu/Menu';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={'bg-white text-gray-900'}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
