import './globals.css';
import React from 'react';
import Layout from '@/components/Layouts/Layout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default Layout;
